# Generated by Django 2.2.4 on 2022-10-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spiecie', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('date_planted', models.DateField()),
                ('planted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='login.User')),
                ('visited_by', models.ManyToManyField(related_name='visited_trees', to='login.User')),
            ],
        ),
    ]
