# Generated by Django 2.2.4 on 2022-10-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbortary', '0002_auto_20221006_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='date_planted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
